### ISSUE TITLE
代码文件编码有误

### ISSUE THREAD

**Issue by the-Rings** [aws-samples/selling-partner-api-bootstrap#13]
我为此付出了很多时间
无论main还是develpoer分支都存在乱码的问题，我是用Jetbrans IDEA来打开项目。这是我遇到的最严重的编码问题。我不知道这个项目是如何测试的，作为官方指定的实例项目，我感到遗憾。
关于AWS合作伙伴动手训练营我已经无力吐槽了，文档有很多地方的残缺。我们必须在各个地方寻找线索来完成文档的阅读。

**Comment by dashjim** [comment]
代码中没有使用英文外的其它字符，您能否提供错误截图和细节？
动手训练营是配合讲师现场讲解的材料。如果不是参加现场的动手训练营的话需要参考官方文档中的细节。

**Comment by dashjim** [comment]
Close as there is no details provided.
